/* eslint-env node */
module.exports = {
	testEnvironment: 'jsdom',
	// Force Node (CJS) resolution so @vue/test-utils loads its Node build rather
	// than the browser bundle, which expects a global Vue.
	testEnvironmentOptions: {
		customExportConditions: [ 'node', 'node-addons' ]
	},
	setupFiles: [ '<rootDir>/tests/jest/setup.js' ],
	testMatch: [ '<rootDir>/tests/jest/**/*.test.js' ],
	moduleFileExtensions: [ 'js', 'json', 'vue' ],
	transform: {
		'^.+\\.js$': 'babel-jest',
		'^.+\\.vue$': '@vue/vue3-jest'
	},
	// The Vue components require '../../codex.js' and '../../icons.json', which are
	// generated by MediaWiki's CodexModule at runtime and do not exist on disk.
	// Map them to local stubs so the SFCs can be imported under Jest.
	moduleNameMapper: {
		'codex\\.js$': '<rootDir>/tests/jest/__mocks__/codex.js',
		'icons\\.json$': '<rootDir>/tests/jest/__mocks__/icons.json'
	}
};
